<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>deneb</AssemblyName><Version>1.1.0</Version></PropertyGroup><ItemGroup><ProjectReference Include="../Deneb.Core/Deneb.Core.csproj"/><PackageReference Include="Terminal.Gui" Version="1.19.0"/></ItemGroup></Project>
