<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>deneb</AssemblyName><Version>2.1.0</Version></PropertyGroup><ItemGroup><ProjectReference Include="../Deneb.Control/Deneb.Control.csproj"/><PackageReference Include="Terminal.Gui" Version="1.19.0"/></ItemGroup></Project>
